@CartonCapsAPI_HostAddress = http://localhost:5037

GET {{CartonCapsAPI_HostAddress}}/api/referral/GetReferralInformation/1
Accept: application/json

###

POST {{CartonCapsAPI_HostAddress}}/api/user/
Accept: application/json

###